# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [1]:
# your code here
import numpy as np

#### 2. Print your NumPy version.

In [2]:
# your code here
print(np.__version__)

1.20.3


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [2]:
# Method 1
a = np.random.random((2, 3, 5))

In [9]:
# Method 2
a = np.random.default_rng(1).random((2, 3, 5))

In [39]:
# Method 3
a = np.random.uniform(0,1,[2,3,5])

#### 4. Print *a*.


In [3]:
# your code here
a

array([[[0.94509023, 0.19572673, 0.24558642, 0.92799071, 0.97027555],
        [0.25908413, 0.08277942, 0.21415298, 0.55274527, 0.50629858],
        [0.97376058, 0.57100738, 0.31810264, 0.12633047, 0.59193631]],

       [[0.19091793, 0.83254139, 0.62896925, 0.24047105, 0.20262669],
        [0.12115194, 0.85966697, 0.10892978, 0.48584753, 0.25665105],
        [0.42475343, 0.25787959, 0.38516581, 0.48527886, 0.03884985]]])

#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [4]:
# your code here
b = np.full((5, 2, 3), 1)

#### 6. Print *b*.


In [5]:
# your code here
b

array([[[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]]])

#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [6]:
# your code here
a.size == b.size

True

#### 8. Are you able to add *a* and *b*? Why or why not?


In [7]:
# your answer here
#c = a + b

#Not working because the shape / structure is not the same

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [8]:
# your code here
c = b.reshape(2, 3, 5)

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [9]:
# your code/answer here        because the shape is the same now
d = a + c
d

array([[[1.94509023, 1.19572673, 1.24558642, 1.92799071, 1.97027555],
        [1.25908413, 1.08277942, 1.21415298, 1.55274527, 1.50629858],
        [1.97376058, 1.57100738, 1.31810264, 1.12633047, 1.59193631]],

       [[1.19091793, 1.83254139, 1.62896925, 1.24047105, 1.20262669],
        [1.12115194, 1.85966697, 1.10892978, 1.48584753, 1.25665105],
        [1.42475343, 1.25787959, 1.38516581, 1.48527886, 1.03884985]]])

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [10]:
# your code/answer here
print(a)
print(d)
print(d-a)

[[[0.94509023 0.19572673 0.24558642 0.92799071 0.97027555]
  [0.25908413 0.08277942 0.21415298 0.55274527 0.50629858]
  [0.97376058 0.57100738 0.31810264 0.12633047 0.59193631]]

 [[0.19091793 0.83254139 0.62896925 0.24047105 0.20262669]
  [0.12115194 0.85966697 0.10892978 0.48584753 0.25665105]
  [0.42475343 0.25787959 0.38516581 0.48527886 0.03884985]]]
[[[1.94509023 1.19572673 1.24558642 1.92799071 1.97027555]
  [1.25908413 1.08277942 1.21415298 1.55274527 1.50629858]
  [1.97376058 1.57100738 1.31810264 1.12633047 1.59193631]]

 [[1.19091793 1.83254139 1.62896925 1.24047105 1.20262669]
  [1.12115194 1.85966697 1.10892978 1.48584753 1.25665105]
  [1.42475343 1.25787959 1.38516581 1.48527886 1.03884985]]]
[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [11]:
# your code here
e = a * c
e

array([[[0.94509023, 0.19572673, 0.24558642, 0.92799071, 0.97027555],
        [0.25908413, 0.08277942, 0.21415298, 0.55274527, 0.50629858],
        [0.97376058, 0.57100738, 0.31810264, 0.12633047, 0.59193631]],

       [[0.19091793, 0.83254139, 0.62896925, 0.24047105, 0.20262669],
        [0.12115194, 0.85966697, 0.10892978, 0.48584753, 0.25665105],
        [0.42475343, 0.25787959, 0.38516581, 0.48527886, 0.03884985]]])

#### 13. Does *e* equal to *a*? Why or why not?


In [12]:
# your code/answer here      because c only value is 1
e == a

array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [13]:
# your code here
d_min = d.min()
d_max = d.max()
d_mean = d.mean()

#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [32]:
# your code here
f = np.empty((2, 3, 5))
f

array([[[7000.94509023, 7000.19572673, 7000.24558642, 7000.92799071,
         7000.97027555],
        [7000.25908413, 7000.08277942, 7000.21415298, 7000.55274527,
         7000.50629858],
        [7000.97376058, 7000.57100738, 7000.31810264, 7000.12633047,
         7000.59193631]],

       [[7000.19091793, 7000.83254139, 7000.62896925, 7000.24047105,
         7000.20262669],
        [7000.12115194, 7000.85966697, 7000.10892978, 7000.48584753,
         7000.25665105],
        [7000.42475343, 7000.25787959, 7000.38516581, 7000.48527886,
         7000.03884985]]])

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [33]:
f= []
for x in np.nditer(d):
    if d_min < x < d_mean:
        f += [25]
    if d_mean < x < d_max:
        f += [75]
    if x == d_mean:
        f += [50]
    if x == d_min:
        f += [0]
    if x == d_max:
        f += [100]

f = np.reshape(f, d.shape)
print(f)

[[[ 75  25  25  75  75]
  [ 25  25  25  75  75]
  [100  75  25  25  75]]

 [[ 25  75  75  25  25]
  [ 25  75  25  75  25]
  [ 25  25  25  75   0]]]


#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [34]:
# your code here
f

array([[[ 75,  25,  25,  75,  75],
        [ 25,  25,  25,  75,  75],
        [100,  75,  25,  25,  75]],

       [[ 25,  75,  75,  25,  25],
        [ 25,  75,  25,  75,  25],
        [ 25,  25,  25,  75,   0]]])

#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [39]:
# your code here
g = []
for x in np.nditer(d):
    if d_min < x < d_mean:
        g += ['B']
    if d_mean < x < d_max:
        g += ['D']
    if x == d_mean:
        g += ['C']
    if x == d_min:
        g += ['A']
    if x == d_max:
        g += ['E']

g = np.reshape(g, d.shape)
print(g)

[[['D' 'B' 'B' 'D' 'D']
  ['B' 'B' 'B' 'D' 'D']
  ['E' 'D' 'B' 'B' 'D']]

 [['B' 'D' 'D' 'B' 'B']
  ['B' 'D' 'B' 'D' 'B']
  ['B' 'B' 'B' 'D' 'A']]]
