## Question 1
The following table indicates the number of 6-point scores in an American rugby match in the 1979 season.

![](table1.png)

Based on these results, we create a Poisson distribution with the sample mean parameter  = 2.435. Is there any reason to believe that at a .05 level the number of scores is a Poisson variable?

In [1]:
# your answer here
import pandas as pd
import numpy as np
import scipy.stats as stats

scores = {'nb_scores':[i for i in range(0,7+1)],
          'nb_times': [35,99,104,110,62,25,10,3]}

score = pd.DataFrame(scores)
score

nb_scores  nb_times
0          0        35
1          1        99
2          2       104
3          3       110
4          4        62
5          5        25
6          6        10
7          7         3

In [11]:
lst = []

for i in range(len(score)):
    lst.extend([score.nb_scores[i]] * score.nb_times[i])

sample = np.array(lst)
np.mean(sample)

2.435267857142857

In [13]:
np.var(sample1) #if variance and mean are close, a poisson distribution might be the case

2.169916892538265

In [14]:
# Compute probability and expected frequency for all categories but the last one
test = stats.poisson.pmf(score.nb_scores[0:-1], np.mean(sample))
r = test * score.nb_times.sum()
r

array([ 39.23328036,  95.54354658, 116.33706397,  94.43730416,
        57.49503284,  28.00316108,  11.36586635])

In [15]:
# Add frequency for the last category
r = np.append(r, score.nb_times.sum() - np.sum(r))
r

array([ 39.23328036,  95.54354658, 116.33706397,  94.43730416,
        57.49503284,  28.00316108,  11.36586635,   5.58474467])

In [17]:
# new col in df
score['expectation'] = r
score

nb_scores  nb_times        test  expectation
0          0        35   39.233280    39.233280
1          1        99   95.543547    95.543547
2          2       104  116.337064   116.337064
3          3       110   94.437304    94.437304
4          4        62   57.495033    57.495033
5          5        25   28.003161    28.003161
6          6        10   11.365866    11.365866
7          7         3    5.584745     5.584745

In [23]:
# Chi-Square test
# hypothesis: the occurrence of scores follows a Poisson distribution
pval = stats.chisquare(f_obs = score.nb_times, f_exp=score.expectation, ddof=1)[1]
pval #pvalue is above 0.05, null hypothesis not rejected

0.3705692339672493

In [5]:
#your answer here
sat = [852, 875, 910, 933, 957, 963, 981, 998, 1010, 1015, 1018, 1023, 1035, 1048, 1063]

np.mean(sat)

978.7333333333333

In [7]:
# hypothesis: mean of a sample of independent observations is equal to the given population mean

pval = stats.ttest_1samp(sat, 985)[1]
pval
# pvalue above 0.05, hypothesis not rejected

0.7059102752345554

In [8]:
np.std(sat)

60.8785311547146

In [9]:
# hypothesis: standard deviation is 50
x = len(sat) - 1
test_stat = ( x * np.std(sat)**2 ) / (50**2)
pval2 = stats.chi2.cdf(test_stat, df = x)
pval2 
# pvalue above 0.05, hypothesis not rejected

0.8919140563821656

In [ ]:
# So both hypothesis are not rejected meaning there has been no change in the distribution of scores

## Question 3
Let's analyze a discrete distribution. To analyze the number of defective items in a factory in the city of Medellín, we took a random sample of n = 60 articles and observed the number of defectives in the following table:

![](table4.png)

A poissón distribution was proposed since it is defined for x = 0,1,2,3, .... using the following model:

![](image1.png)

Does the distribution of defective items follow this distribution?

In [25]:
# your code here
#Same process as in question 1

defective = {'nb_defects':[0,1,3,4,5],
             'obs_freq': [32,15,9,4,0]}

item = pd.DataFrame(defective)
item

nb_defects  obs_freq
0           0        32
1           1        15
2           3         9
3           4         4
4           5         0

In [27]:
lst = []

for i in range(len(item)):
    lst.extend([item.nb_defects[i]] * item.obs_freq[i])

sample1 = np.array(lst)
np.mean(sample1)

0.9666666666666667

In [28]:
#much different from mean, so it should not follow a Poisson distribution
np.var(sample1)

1.7322222222222228

In [29]:
probability = stats.poisson.pmf(item.nb_defects[0:-1], np.mean(sample1))
expectation = probability * item.obs_freq.sum()
expectation

array([22.8209254 , 22.06022788,  3.43567623,  0.83028842])

In [32]:
expectation = np.append(expectation, item.obs_freq.sum() - np.sum(expectation))
expectation #result should not be that

array([ 22.8209254 ,  22.06022788,   3.43567623,   0.83028842,
        47.        ,   0.        , -36.14711793,   0.        ])

In [33]:
item['expectation'] = expectation
item #not working because of weird value before

ValueError: Length of values (8) does not match length of index (5)

In [ ]:
# hypothesis: the occurrence of scores follows a Poisson distribution
pval = stats.chisquare(f_obs = item.obs_freq, f_exp=item.exp_freq, ddof=1)[1]
pval   #can't find result without fixing previous problem

## Question 4
A quality control engineer takes a simple of 10 tires that come out of an assembly line, and would like to verify on the basis of the data that follows, if the number of tires with defects observed over 200 days, if it is true that 5% of all tires have defects (that is, if the sample comes from a binomial population with n = 10 and p = 0.05). 

In [34]:
# your answer here
# Create a sample
sample = np.random.binomial(n=10,p=0.05, size=200)
sample

array([2, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 2, 0, 0, 0, 0, 0,
       2, 0, 0, 2, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 2,
       1, 1, 1, 0, 2, 0, 0, 1, 1, 0, 0, 0, 0, 2, 1, 1, 0, 0, 0, 1, 0, 0,
       1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0, 0,
       2, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0,
       0, 2, 2, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0,
       2, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 2, 0, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       1, 1])

## Question 5
A researcher gathers information about the patterns of physical activity (AF) of children in the fifth grade of primary school of a public school. He defines three categories of physical activity (1 = Low, 2 = Medium, 3 = High). He also inquires about the regular consumption of sugary drinks at school, and defines two categories (1 = consumed, 0 = not consumed). We would like to evaluate if there is an association between patterns of physical activity and the consumption of sugary drinks for the children of this school, at a level of 5% significance. The results are in the following table: 

![](table5.png)

In [4]:
#your answer here
sport = {'physical_activity':['Low','Medium','High'],
         'Yes':[32,14,6],
         'No': [12,22,9]}

children = pd.DataFrame(sport)
children = pd.melt(children, id_vars=['physical_activity'], value_vars = ['Yes', 'No'], var_name='consume_sugardrinks', value_name='nb')
children

physical_activity consume_sugardrinks  nb
0               Low                 Yes  32
1            Medium                 Yes  14
2              High                 Yes   6
3               Low                  No  12
4            Medium                  No  22
5              High                  No   9

In [5]:
cross = pd.crosstab(index=children.physical_activity, columns = children.consume_sugardrinks, values = children.nb, aggfunc = np.sum)
cross

consume_sugardrinks  No  Yes
physical_activity           
High                  9    6
Low                  12   32
Medium               22   14

In [ ]:
# Chi-square test of independence of variable

chi2, p, dof, expected = stats.chi2_contingency(cross)
p # pvalue below 0.05, null hypothesis rejected
# Meaning, there is link between physical activity and the consumption of sugary drinks